language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.2.7
  - DJANGO=1.3.1
  - DJANGO=1.4
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install nose==1.1.2
  - pip install django-nose==0.1.3
  - pip install coverage==3.5.1
  - pip install django-dynamic-fixture==1.6.1
  - pip install https://github.com/paulocheque/django-intruder/tarball/master
  - pip install --quiet -e .
script:
  - python runtests.py
